#!/bin/bash 

# skip pv check if parms are not correctly provided 

if [ -z "$1" -o -z "$2" -o -z "$3" ]; then
   exit 0
fi
if [ `echo "$2" | wc -l` -ne 1 ]; then 
   exit 0
fi
if ! echo "$2" | grep -E "^[1-9][0-9]*$" >/dev/null; then
   exit 0
fi
exit 1

# end


